### ISSUE TITLE
Cannot get the app_config if the module is in a sub-directory

### ISSUE THREAD

**Issue by wyhfrank** [synw/django-introspection#1]
## Description of the problem

If I have an app in a sub-directory with a path of, say, `apps/myapp/`, then the AppConfig will usually be something like:

``` python
class MyAppConfig(AppConfig):
    name = 'apps.myapp'
    label = 'apps_myapp'
```

Note that the `label` is different than its `name`, since dots cannot be included in a label. (See [this doc](https://docs.djangoproject.com/en/3.2/ref/applications/#django.apps.AppConfig.label) )
By default, `label` will be the last part of the `name`, in the case above, the default label would be `myapp`, still different than its `name`.

It will be registered in the `settings.py` as:

``` py
INSTALLED_APPS = [
     ...
    'apps.myapp',
]
```

Then here comes the problem, in the following code, the `app_config` is retrieved with `apps.get_app_config()`:

https://github.com/synw/django-introspection/blob/3d22f4850b0b67a8ca5e3ad413a716de13f14908/introspection/inspector/inspector.py#L25

However, the `apps.get_app_config()` takes the `label` instead of `name` of the app as a parameter (see [this doc](https://docs.djangoproject.com/en/3.2/ref/applications/#django.apps.apps.get_app_config)), thus in the example above, the `apps.myapp` will fail to be retrieved.

## A possible solution

Instead of:

https://github.com/synw/django-introspection/blob/3d22f4850b0b67a8ca5e3ad413a716de13f14908/introspection/inspector/inspector.py#L23-L26

do this:

``` py
        for tmp in APPS.get_app_configs():
            if tmp.name == name:
                app_config = tmp
                break
```

**Comment by synw** [comment]
Thanks for reporting this. Would you like to offer a PR or shall I do the fix?

**Comment by wyhfrank** [comment]
Thanks for replying.

I would like to offer a PR definitly, but I am not quite familiar with developing a django module, especially installing the dependencies and running the test cases. So it would be nice if you could add some documentation (or simple instructions) on setting up the development environment. Or simply pointing me to some links of online resources like tutorials etc. will help a lot.

Or if you would prefer fixing this by yourself since it takes less efforts, please go ahead. ;)

**Comment by synw** [comment]
What you could do: fork the repo and clone it locally. In some django project uninstall django-introspection and create a symlink into your django project to have it running your fork:

```bash
cd /some/dev/dir
git clone https://github.com/wyhfrank/django-introspection.git
cd /my/django/project
ln -s /some/dev/dir/django-introspection/introspection introspection
```
This way you can run a local copy of introspection and change the code.

To run the tests install [tox](https://pypi.org/project/tox/) and in the django-introspection folder run the command: `tox`

**Comment by synw** [comment]
@wyhfrank I moved the tests to pytest and made a nicer test infrastructure: https://github.com/synw/django-introspection#run-the-tests , easier to run

**Comment by synw** [comment]
I refactored and improved your suggested fix to be able to load app configs either from a label or a path. It should work in 0.8.2

**Comment by wyhfrank** [comment]
> I refactored and improved your suggested fix to be able to load app configs either from a label or a path. It should work in 0.8.2

Wow, thank you so much! Looks awesome! (and sorry I was a little busy and couldn't fix this issue)
